"""
Phase 1: Core Context, State, and Data Structures
All shared types used across the cognitive pipeline.
"""

import time
import uuid
from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional
from enum import Enum


class TaskState(Enum):
    PENDING = "pending"
    PLANNING = "planning"
    EXECUTING = "executing"
    VERIFYING = "verifying"
    REFINING = "refining"
    COMPLETED = "completed"
    FAILED = "failed"


class Confidence(Enum):
    VERY_LOW = (0.0, 0.4)
    LOW = (0.4, 0.6)
    MEDIUM = (0.6, 0.75)
    HIGH = (0.75, 0.9)
    VERY_HIGH = (0.9, 1.0)

    @classmethod
    def from_score(cls, score: float) -> "Confidence":
        for level in cls:
            lo, hi = level.value
            if lo <= score < hi:
                return level
        return cls.VERY_HIGH


@dataclass
class ExecutionContext:
    """
    Carries all state for a single task execution.
    Passed through the entire protocol pipeline.
    """
    task: str
    session_id: str
    context: Dict[str, Any] = field(default_factory=dict)
    working_memory: Any = None
    episodic_memory: Any = None
    state: TaskState = TaskState.PENDING
    created_at: float = field(default_factory=time.time)
    updates: Dict[str, Any] = field(default_factory=dict)
    error: Optional[str] = None

    def update(self, key: str, value: Any):
        self.updates[key] = value
        if self.working_memory:
            try:
                import asyncio
                loop = asyncio.get_event_loop()
                if loop.is_running():
                    asyncio.ensure_future(
                        self.working_memory.store(f"ctx:{key}", value)
                    )
            except Exception as err:
                import logging
                logging.getLogger(__name__).error("Exception swallowed: %s", err)
                raise RuntimeError(f"Exception swallowed: {err}")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "task": self.task,
            "session_id": self.session_id,
            "context": self.context,
            "state": self.state.value,
            "updates": self.updates,
            "created_at": self.created_at
        }

    def get(self, key: str, default: Any = None) -> Any:
        return self.updates.get(key, self.context.get(key, default))


@dataclass
class ReasoningPath:
    """Single reasoning path generated by the multi-path engine."""
    path_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    model: str = ""
    strategy: str = ""
    reasoning: str = ""
    output: str = ""
    confidence: float = 0.0
    token_count: int = 0
    latency_ms: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict:
        return asdict(self)


@dataclass
class GenerationResult:
    """Aggregated output from the multi-path or debate engine."""
    task: str
    all_paths: List[ReasoningPath] = field(default_factory=list)
    best_path: Optional[ReasoningPath] = None
    consensus: Optional[str] = None
    divergence_score: float = 0.0
    generation_strategy: str = "multi_path"
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def best_output(self) -> str:
        if self.consensus:
            return self.consensus
        if self.best_path:
            return self.best_path.output
        if self.all_paths:
            return max(self.all_paths, key=lambda p: p.confidence).output
        return ""

    @property
    def summary(self) -> str:
        return self.best_output[:200] + "..." if len(self.best_output) > 200 else self.best_output

    def to_dict(self) -> Dict:
        return {
            "task": self.task,
            "best_output": self.best_output,
            "all_paths": [p.to_dict() for p in self.all_paths],
            "consensus": self.consensus,
            "divergence_score": self.divergence_score,
            "generation_strategy": self.generation_strategy,
            "metadata": self.metadata
        }


@dataclass
class TaskPlan:
    """Structured plan produced by the TaskPlanner."""
    plan_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    task: str = ""
    goal: str = ""
    sub_tasks: List[Dict[str, Any]] = field(default_factory=list)
    required_agents: List[str] = field(default_factory=list)
    required_tools: List[str] = field(default_factory=list)
    strategy: str = "default"
    requires_debate: bool = False
    requires_execution: bool = False
    estimated_complexity: str = "medium"
    constraints: List[str] = field(default_factory=list)
    success_criteria: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict:
        return asdict(self)


@dataclass
class EvaluationResult:
    """Output from the ReasoningEvaluator."""
    score: float = 0.0
    passed: bool = False
    issues: List[str] = field(default_factory=list)
    strengths: List[str] = field(default_factory=list)
    suggested_changes: List[str] = field(default_factory=list)
    requires_strategy_shift: bool = False
    best_path_id: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict:
        return asdict(self)


@dataclass
class MemoryEntry:
    """Generic memory entry used across memory systems."""
    entry_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    content: Any = None
    content_type: str = "text"
    tags: List[str] = field(default_factory=list)
    importance: float = 0.5
    created_at: float = field(default_factory=time.time)
    accessed_at: float = field(default_factory=time.time)
    access_count: int = 0
    session_id: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict:
        return asdict(self)

    def touch(self):
        self.accessed_at = time.time()
        self.access_count += 1


@dataclass
class AgentMessage:
    """Inter-agent communication message."""
    msg_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    sender: str = ""
    receiver: str = ""
    content: Any = None
    msg_type: str = "task"
    priority: int = 5
    timestamp: float = field(default_factory=time.time)
    reply_to: Optional[str] = None

    def to_dict(self) -> Dict:
        return asdict(self)


@dataclass
class ToolCall:
    """A tool invocation record."""
    call_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    tool_name: str = ""
    arguments: Dict[str, Any] = field(default_factory=dict)
    result: Any = None
    success: bool = False
    error: Optional[str] = None
    latency_ms: float = 0.0
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> Dict:
        return asdict(self)

class IdentityKernel:
    """Core identity configuration and alignment checker."""
    def check_alignment(self, context: Any, candidate: Any) -> bool:
        return True
        
    def resolve_conflict(self, conflict: Dict[str, Any]) -> Dict[str, Any]:
        return {"resolved": True, "conflict": conflict}
