from __future__ import annotations

from typing import Any, AsyncIterator, Protocol

from core.runtime.context import RuntimeContext


class MemoryService(Protocol):
    async def store_facts(self, ctx: RuntimeContext, facts: list[dict[str, Any]]) -> int: ...
    async def search_facts(self, ctx: RuntimeContext, query: str, **kwargs: Any) -> list[dict[str, Any]]: ...
    async def get_user_facts(self, ctx: RuntimeContext, user_id: str) -> list[dict[str, Any]]: ...


class ObservationService(Protocol):
    async def publish(self, ctx: RuntimeContext, observation: Any) -> None: ...


class SchedulerService(Protocol):
    async def create_activity(self, ctx: RuntimeContext, goal: str, **kwargs: Any) -> str: ...
    async def get_queue(self, ctx: RuntimeContext) -> list[Any]: ...


class MetricsService(Protocol):
    def record(self, ctx: RuntimeContext, metrics: dict[str, Any]) -> None: ...


class EventBusProtocol(Protocol):
    async def publish(self, ctx: RuntimeContext, event: Any) -> None: ...
    async def subscribe(self, ctx: RuntimeContext, handler: Any) -> None: ...


class ActivityService(Protocol):
    async def create_activity(self, ctx: RuntimeContext, goal: str) -> Any: ...
    async def create_node(self, ctx: RuntimeContext, activity_id: str, **kwargs: Any) -> Any: ...
