from core.workspace.window_detector import WindowDetector
from core.workspace.browser_context import BrowserContextAwareness
from core.workspace.clipboard_manager import ClipboardManager
from core.workspace.process_monitor import ProcessMonitor
from core.workspace.desktop_state import DesktopState
