// lib/firebase_options.dart
// !! REPLACE THIS FILE by running: flutterfire configure
// This is a placeholder — the real file is auto-generated by FlutterFire CLI

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: return android;
      case TargetPlatform.iOS:     return ios;
      case TargetPlatform.windows: return windows;
      default: throw UnsupportedError('DefaultFirebaseOptions not supported for ${defaultTargetPlatform.name}');
    }
  }

  // !! Replace all values below with your actual Firebase config !!
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: '1:YOUR_APP_ID:android:YOUR_HASH',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'your-jarvis-project',
    storageBucket: 'your-jarvis-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:YOUR_APP_ID:ios:YOUR_HASH',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'your-jarvis-project',
    storageBucket: 'your-jarvis-project.appspot.com',
    iosBundleId: 'com.yourname.jarvisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:YOUR_APP_ID:web:YOUR_HASH',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'your-jarvis-project',
    storageBucket: 'your-jarvis-project.appspot.com',
    authDomain: 'your-jarvis-project.firebaseapp.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:YOUR_APP_ID:web:YOUR_HASH',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'your-jarvis-project',
    storageBucket: 'your-jarvis-project.appspot.com',
    authDomain: 'your-jarvis-project.firebaseapp.com',
  );
}
