import { useState } from 'react';
import { BrowserRouter, NavLink, Route, Routes, useLocation } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import {
  activity, agents, analytics, artifacts, dashboard, diagnostics, memory, plans, research,
  scheduler, settings, workflows, chat, models, projects, knowledge,
  type Artifact, type Agent, type ActivityNode, type Plan, type Schedule, type Project, type KnowledgeItem,
  type MemoryEntry, reminders, notes, files,
} from '@jarvis/sdk';
import { EmptyState, PageFrame } from './components';

type SettingItem = Awaited<ReturnType<typeof settings.list>>[number];

type Page = { key: string; label: string; icon: string; group: string };
const pages: Page[] = [
  ['dashboard','Dashboard','⌂','Overview'],['activity','Activity','◌','Overview'],['chat','Chat','✦','Operate'],['agents','Agents','◎','Operate'],['workflows','Workflows','◇','Operate'],['plans','Plans','▤','Operate'],['schedules','Schedules','◷','Operate'],['knowledge','Knowledge','⌘','Intelligence'],['research','Research','⌕','Intelligence'],['artifacts','Artifacts','▧','Intelligence'],['analytics','Analytics','◒','Intelligence'],['opportunities','Opportunities','↗','Intelligence'],['negotiations','Negotiations','⇄','Intelligence'],['horizon','Horizon','◈','Intelligence'],['commitments','Commitments','✓','Workspace'],['reminders','Reminders','!','Workspace'],['notes','Notes','≡','Workspace'],['projects','Projects','▦','Workspace'],['build','Build','⚙','Workspace'],['code','Code','</>','Workspace'],['files','Files','□','Workspace'],['email','Email','✉','Connect'],['channels','Channels','#','Connect'],['integrations','Integrations','⊕','Connect'],['plugins','Plugins','⌬','Connect'],['skills','Skills','✺','Connect'],['models','Models','◉','Connect'],['memory','Memory','▥','System'],['diagnostics','Diagnostics','⌁','System'],['settings','Settings','⚙','System'],
].map(([key,label,icon,group])=>({key,label,icon,group}));

/** Source-of-truth page → typed SDK endpoint mapping for Phase 2. */
export const pageEndpointMap = {
  dashboard: ['/api/stats', '/api/monthly-highlights'],
  activity: ['/api/activity', '/api/activity/counts'],
  agents: ['/api/v1/agents/'],
  workflows: ['/api/workflows'],
  plans: ['/api/plans'],
  schedules: ['/api/schedules'],
  research: ['/api/research/statistics', '/api/research/facts?limit=50'],
  artifacts: ['/api/artifacts'],
  analytics: ['/api/analytics/planner-performance'],
  memory: ['/api/memory', '/api/memory/stats'],
  diagnostics: ['/api/diagnostics'],
  settings: ['/api/settings', '/api/settings/{key} (PUT)'],
  projects: ['/projects'],
  knowledge: ['/api/knowledge', '/api/knowledge/statistics', '/api/knowledge/search'],
} as const;

export default function App(){return <BrowserRouter><Shell/></BrowserRouter>}
function Shell(){const [collapsed,setCollapsed]=useState(false);const location=useLocation();const page=pages.find(p=>location.pathname.includes(`/${p.key}`))??pages[0];return <div className={`app ${collapsed?'collapsed':''}`}><aside className="sidebar"><div className="brand"><div className="orb">J</div>{!collapsed&&<div><strong>JARVIS</strong><small>AGENT OS <i>●</i></small></div>}</div><nav className="nav">{Array.from(new Set(pages.map(p=>p.group))).map(group=><section key={group}><label>{!collapsed&&group}</label>{pages.filter(p=>p.group===group).map(p=><NavLink end to={`/${p.key}`} key={p.key} title={p.label}><span>{p.icon}</span>{!collapsed&&p.label}</NavLink>)}</section>)}</nav><div className="profile"><div className="avatar">PS</div>{!collapsed&&<div><strong>Peter S.</strong><small>Operator · Online</small></div>}</div></aside><main><header><button className="menu" onClick={()=>setCollapsed(v=>!v)}>☰</button><div className="crumb">JARVIS <span>/</span> {page.label.toUpperCase()}</div></header><div className="content"><Routes>{pages.map(p=><Route key={p.key} path={`/${p.key}`} element={<PageRoute page={p}/>}/>)}</Routes></div></main></div>}

function State({ query, children }: { query: { isLoading: boolean; isError: boolean; error: unknown; refetch: () => void }; children: React.ReactNode }) {
  if (query.isLoading) return <div className="loading">Loading…</div>;
  if (query.isError) return <div className="error">{query.error instanceof Error ? query.error.message : 'Unable to load data'} <button onClick={() => query.refetch()}>Retry</button></div>;
  return <>{children}</>;
}
function ListCard<T>({ query, items, empty, render }: { query: any; items: T[]; empty: string; render: (item:T)=>React.ReactNode }) {
  return <article className="wide"><State query={query}>{items.length === 0 ? <EmptyState title={empty} description="The API returned no records yet."/> : <div className="artifact-list">{items.map(render)}</div>}</State></article>;
}
function Metric({label,value,detail}:{label:string;value:React.ReactNode;detail?:string}){return <div className="metric-card"><small>{label}</small><b>{value}</b>{detail&&<span>{detail}</span>}</div>}
function statusClass(status:string){return status.toLowerCase().replace('_','-')}
function DashboardPage(){const stats=useQuery({queryKey:['dashboard','stats'],queryFn:()=>dashboard.stats()});const highlights=useQuery({queryKey:['dashboard','highlights'],queryFn:()=>dashboard.highlights()});return <PageFrame eyebrow="OVERVIEW" title="Dashboard" description="Live operational health from JARVIS services."><State query={stats}>{stats.data&&<section className="metric-grid"><Metric label="GPU VRAM" value={stats.data.gpu_vram} detail={`${stats.data.gpu_pct}% utilized`}/><Metric label="Hot memory" value={stats.data.memory_hot}/><Metric label="Cold memory" value={stats.data.memory_cold}/><Metric label="Searches" value={stats.data.search_queries}/><Metric label="Commands" value={stats.data.commands}/><Metric label="Reminders" value={stats.data.reminders}/><Metric label="Notes" value={stats.data.notes}/></section>}</State><State query={highlights}>{highlights.data&&<article className="wide highlight-card"><div className="section-heading"><div><span className="eyebrow">MONTHLY PULSE</span><h3>{highlights.data.month}</h3></div><span className="type-badge">{highlights.data.top_models.length} models</span></div><div className="metric-grid compact"><Metric label="Conversations" value={highlights.data.conversations}/><Metric label="Commands run" value={highlights.data.commands_executed}/><Metric label="Searches" value={highlights.data.searches}/><Metric label="Reminders" value={highlights.data.reminders}/></div>{highlights.data.top_models.length>0?<div className="tag-list">{highlights.data.top_models.map(model=><span className="type-badge" key={model}>{model}</span>)}</div>:<EmptyState title="No model activity yet" description="Monthly model usage will appear here when available."/>}</article>}</State></PageFrame>}
function ActivityPage(){const q=useQuery({queryKey:['activity'],queryFn:activity.list});const counts=useQuery({queryKey:['activity','counts'],queryFn:activity.counts});const cancel=useMutation({mutationFn:(id:string)=>activity.cancel(id),onSuccess:()=>q.refetch()});return <PageFrame eyebrow="OVERVIEW" title="Activity" description="Track active work and execution status."><State query={counts}>{counts.data&&<section className="metric-grid compact activity-summary"><Metric label="Total" value={counts.data.total}/><Metric label="Running" value={counts.data.running}/><Metric label="Pending" value={counts.data.pending}/><Metric label="Completed" value={counts.data.completed}/><Metric label="Failed" value={counts.data.failed}/><Metric label="Suspended" value={counts.data.suspended}/></section>}</State><ListCard query={q} items={(q.data??[]) as ActivityNode[]} empty="No active activities" render={a=><div className="artifact activity-row" key={a.node_id}><span className={`status-pill ${statusClass(a.status)}`}>{a.status}</span><div><b>{a.label||'Untitled activity'}</b><small>{a.node_type.replace('_',' ')} · {a.activity_id}{a.agent_id?` · ${a.agent_id}`:''}</small></div>{['RUNNING','PENDING','SUSPENDED'].includes(a.status)&&<button onClick={()=>cancel.mutate(a.activity_id)} disabled={cancel.isPending}>Cancel</button>}</div>}/></PageFrame>}
function AgentsPage(){const q=useQuery({queryKey:['agents'],queryFn:agents.list});return <PageFrame eyebrow="OPERATE" title="Agents" description="Inspect available agents and their current state."><ListCard query={q} items={(q.data??[]) as Agent[]} empty="No agents registered" render={a=><div className="artifact" key={a.name}><div><b>{a.display_name||a.name}</b><small>{a.status} · {a.description||'No description'}</small></div><span>{a.default_mode||'default'}</span></div>}/></PageFrame>}
function WorkflowsPage(){const q=useQuery({queryKey:['workflows'],queryFn:()=>workflows.list(undefined,50)});const qc=useQueryClient();const mutate=useMutation<unknown, Error, {id:string;action:'cancel'|'resume'}>({mutationFn:(x)=>x.action==='cancel'?workflows.cancel(x.id):workflows.resume(x.id),onSuccess:()=>qc.invalidateQueries({queryKey:['workflows']})});return <PageFrame eyebrow="OPERATE" title="Workflows" description="Monitor and safely control workflow execution."><ListCard query={q} items={q.data?.workflows??[]} empty="No workflows" render={w=><div className="artifact" key={w.workflow_id}><div><b>{w.workflow_type}</b><small>{w.status} · {w.progress}</small></div>{w.status==='RUNNING'&&<button onClick={()=>mutate.mutate({id:w.workflow_id,action:'cancel'})}>Cancel</button>}{['FAILED','PAUSED'].includes(w.status)&&<button onClick={()=>mutate.mutate({id:w.workflow_id,action:'resume'})}>Resume</button>}</div>}/></PageFrame>}
function PlansPage(){const q=useQuery({queryKey:['plans'],queryFn:()=>plans.list()});const qc=useQueryClient();const mutate=useMutation({mutationFn:(x:{id:string;action:'approve'|'execute'|'reject'})=>plans[x.action](x.id),onSuccess:()=>qc.invalidateQueries({queryKey:['plans']})});return <PageFrame eyebrow="OPERATE" title="Plans" description="Review plans before they execute."><ListCard query={q} items={(q.data?.plans??[]) as Plan[]} empty="No plans" render={p=><div className="artifact" key={p.id}><div><b>{p.goal}</b><small>{p.status}</small></div>{p.status==='draft'&&<button onClick={()=>mutate.mutate({id:p.id,action:'approve'})}>Approve</button>}{p.status==='approved'&&<button onClick={()=>mutate.mutate({id:p.id,action:'execute'})}>Execute</button>}</div>}/></PageFrame>}
function SchedulesPage(){const q=useQuery({queryKey:['schedules'],queryFn:()=>scheduler.list()});const qc=useQueryClient();const mutate=useMutation({mutationFn:(x:{id:string;paused:boolean})=>x.paused?scheduler.resume(x.id):scheduler.pause(x.id),onSuccess:()=>qc.invalidateQueries({queryKey:['schedules']})});return <PageFrame eyebrow="OPERATE" title="Schedules" description="Manage recurring automations."><ListCard query={q} items={(q.data?.schedules??[]) as Schedule[]} empty="No schedules" render={s=><div className="artifact" key={s.id}><div><b>{s.name}</b><small>{s.status} · {s.cron||`${s.interval_seconds||0}s interval`}</small></div>{(s.status==='active'||s.status==='paused')&&<button onClick={()=>mutate.mutate({id:s.id,paused:s.status==='paused'})}>{s.status==='paused'?'Resume':'Pause'}</button>}</div>}/></PageFrame>}
function ResearchPage(){const q=useQuery({queryKey:['research','facts'],queryFn:()=>research.listFacts({limit:50})});const s=useQuery({queryKey:['research','stats'],queryFn:research.statistics});return <PageFrame eyebrow="INTELLIGENCE" title="Research" description="Browse sourced facts and research statistics."><State query={s}><article className="wide"><pre>{JSON.stringify(s.data,null,2)}</pre></article></State><ListCard query={q} items={q.data?.facts??[]} empty="No research facts" render={f=><div className="artifact" key={f.fact_id}><div><b>{f.claim}</b><small>{f.category} · {Math.round(f.confidence*100)}% · {f.source_url}</small></div></div>}/></PageFrame>}
function ArtifactsPage(){const [offset,setOffset]=useState(0);const q=useQuery({queryKey:['artifacts',offset],queryFn:()=>artifacts.list({limit:20,offset})});const items=q.data?.artifacts??[];return <PageFrame eyebrow="INTELLIGENCE" title="Artifacts" description="Everything your agents have made, in one place."><ListCard query={q} items={items as Artifact[]} empty="No artifacts yet" render={a=><div className="artifact" key={a.artifact_id}><div><b>{a.name||'Untitled artifact'}</b><small>{a.artifact_type} · {a.size_bytes} bytes</small></div><a href={artifacts.downloadUrl(a.artifact_id)} download>Download ↓</a></div>}/>{(q.data?.total??0)>20&&<div className="pager"><button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-20))}>Previous</button><button disabled={offset+20>=(q.data?.total??0)} onClick={()=>setOffset(offset+20)}>Next</button></div>}</PageFrame>}
function AnalyticsPage(){const q=useQuery({queryKey:['analytics'],queryFn:analytics.plannerPerformance});return <PageFrame eyebrow="INTELLIGENCE" title="Analytics" description="Planner performance and prediction accuracy."><State query={q}>{q.data&&<><section className="metric-grid"><Metric label="Plans" value={q.data.overall.total_plans} detail={`${q.data.overall.completed_plans} completed`}/><Metric label="Success rate" value={`${Math.round(q.data.overall.success_rate*100)}%`} detail={`${q.data.overall.successful} successful`}/><Metric label="Prediction accuracy" value={q.data.overall.avg_prediction_accuracy==null?'—':`${Math.round(q.data.overall.avg_prediction_accuracy*100)}%`}/><Metric label="Replan rate" value={`${Math.round(q.data.replan_metrics.replan_rate*100)}%`} detail={`${q.data.replan_metrics.replanned_count} replanned`}/></section><section className="analytics-layout"><article className="wide"><div className="section-heading"><div><span className="eyebrow">STRATEGIES</span><h3>Strategy win rates</h3></div></div>{q.data.strategy_win_rates.length===0?<EmptyState title="No strategy data yet" description="Strategy comparisons appear after plans complete."/>:<div className="table-list">{q.data.strategy_win_rates.map(strategy=><div className="table-row" key={strategy.strategy}><b>{strategy.strategy}</b><span>{strategy.successful}/{strategy.total} wins</span><strong>{Math.round(strategy.win_rate*100)}%</strong></div>)}</div>}</article><article className="wide"><div className="section-heading"><div><span className="eyebrow">CALIBRATION</span><h3>Confidence signal</h3></div><span className="status-pill">{q.data.confidence_calibration.status}</span></div><p className="panel-copy">{q.data.confidence_calibration.avg_calibration_error==null?'Not enough completed plans to assess calibration.':`Average calibration error: ${Math.round(q.data.confidence_calibration.avg_calibration_error*100)}%.`}</p><div className="table-list">{q.data.accuracy_trend.recent.slice(-5).map(point=><div className="table-row" key={point.plan_id}><span>{new Date(point.completed_at).toLocaleDateString()}</span><strong>{Math.round(point.accuracy*100)}%</strong></div>)}</div></article></section></>}</State></PageFrame>}
function MemoryPage(){const q=useQuery({queryKey:['memory'],queryFn:memory.list});const s=useQuery({queryKey:['memory','stats'],queryFn:memory.stats});return <PageFrame eyebrow="SYSTEM" title="Memory" description="Inspect retained operator context."><State query={s}>{s.data&&<section className="metric-grid compact"><Metric label="Total memories" value={s.data.total}/><Metric label="Total entries" value={s.data.total_entries??s.data.total}/><Metric label="Vector index" value={s.data.vector_count??0}/><Metric label="Episodic" value={s.data.episodic_count??0}/><Metric label="Semantic" value={s.data.semantic_count??0}/></section>}</State><ListCard<MemoryEntry> query={q} items={q.data??[]} empty="No memory entries" render={m=><div className="artifact memory-row" key={m.id}><span className="status-pill">{m.type}</span><div><b>{m.content||'Untitled memory'}</b><small>{new Date(m.timestamp).toLocaleString()}{m.tags?.length?` · ${m.tags.join(', ')}`:''}</small></div></div>}/></PageFrame>}
function DiagnosticsPage(){const q=useQuery({queryKey:['diagnostics'],queryFn:diagnostics.all});return <PageFrame eyebrow="SYSTEM" title="Diagnostics" description="Service health and dependency checks."><State query={q}>{q.data&&<><article className="wide diagnostics-overview"><div className="diagnostics-status"><span className={`status-badge ${q.data.status}`}>{q.data.status}</span><div><h3>System health</h3><p>{q.data.status==='ok'?'All reported systems are operating normally.':q.data.status==='degraded'?'Some systems need attention.':'One or more systems reported an error.'}</p></div></div><div className="diagnostics-summary"><div><small>Services</small><b>{Object.keys(q.data.services).length}</b></div><div><small>Warnings</small><b>{q.data.warnings.length}</b></div><div><small>Errors</small><b>{q.data.errors.length}</b></div></div></article><section className="diagnostics-layout"><article className="diagnostics-panel"><div className="section-heading"><div><span className="eyebrow">SERVICE MAP</span><h3>Dependencies</h3></div><span className="section-count">{Object.keys(q.data.services).length}</span></div><div className="service-grid">{Object.entries(q.data.services).map(([name,service])=><div className="service-card" key={name}><div className={`service-indicator ${service.status.toLowerCase()}`}/><div><b>{name.replaceAll('_',' ')}</b><small>{service.message||'No additional details'}</small></div><span className="status-label">{service.status}</span></div>)}</div></article><article className="diagnostics-panel"><div className="section-heading"><div><span className="eyebrow">CAPABILITIES</span><h3>Runtime checks</h3></div></div><div className="capability-list">{[['Models',q.data.models_available],['Integrations',q.data.integrations_available],['Storage',q.data.storage_available],['Memory',q.data.memory_available]].map(([label,available])=><div className="capability-row" key={String(label)}><span>{String(label)}</span><strong className={available?'available':'unavailable'}>{available?'Available':'Unavailable'}</strong></div>)}</div></article></section>{(q.data.warnings.length>0||q.data.errors.length>0)&&<article className="wide diagnostics-messages"><div className="section-heading"><div><span className="eyebrow">ATTENTION</span><h3>Warnings and errors</h3></div></div>{q.data.errors.map((message,i)=><div className="diagnostic-message error-message" key={`error-${i}`}><b>Error</b><span>{message}</span></div>)}{q.data.warnings.map((message,i)=><div className="diagnostic-message warning-message" key={`warning-${i}`}><b>Warning</b><span>{message}</span></div>)}</article>}</>}</State></PageFrame>}
function settingValue(value: unknown){if(value===null||value===undefined)return 'Not set';if(typeof value==='boolean')return value?'Enabled':'Disabled';if(typeof value==='object'){try{return JSON.stringify(value)}catch{return 'Configured'}}return String(value)}
function SettingsPage(){const q=useQuery({queryKey:['settings'],queryFn:()=>settings.list()});const qc=useQueryClient();const mutate=useMutation({mutationFn:({key,value}:{key:string;value:unknown})=>settings.update(key,value),onSuccess:()=>qc.invalidateQueries({queryKey:['settings']})});const grouped=(q.data??[]).reduce<Record<string,SettingItem[]>>((groups,setting)=>{const category=setting.category||'General';(groups[category]??=[]).push(setting);return groups},{});return <PageFrame eyebrow="SYSTEM" title="Settings" description="Review and update runtime configuration safely."><State query={q}><div className="settings-sections">{Object.entries(grouped).map(([category,items])=><section className="settings-section" key={category}><div className="section-heading"><div><span className="eyebrow">CONFIGURATION</span><h3>{category}</h3></div><span className="section-count">{items.length}</span></div><div className="settings-grid">{items.map(s=><div className="setting-card" key={s.key}><div className="setting-card-header"><div><b>{s.label||s.key}</b><small>{s.key}</small></div><span className="type-badge">{s.type}</span></div><p>{s.description||'No description provided.'}</p><div className="setting-value"><span>Current value</span><strong>{settingValue(s.value)}</strong></div><div className="setting-footer">{s.restart_required&&<span className="restart-badge">Restart required</span>}<button disabled={mutate.isPending} onClick={()=>mutate.mutate({key:s.key,value:s.value})}>Save current</button></div></div>)}</div></section>)}</div></State></PageFrame>}
function ModelsPage(){const q=useQuery({queryKey:['models'],queryFn:models.list});const groups=useQuery({queryKey:['models','groups'],queryFn:models.groups});const qc=useQueryClient();const [selected,setSelected]=useState('');const current=selected||groups.data?.groups?.chat||q.data?.default||'';const save=useMutation({mutationFn:(value:string)=>settings.update('llm.chat_model',value),onSuccess:()=>{qc.invalidateQueries({queryKey:['models','groups']});setSelected('')}});return <PageFrame eyebrow="CONNECT" title="Models" description="Choose the model used for chat. Models are discovered from Ollama when it is available."><State query={q}><article className="wide"><div className="setting-card-header"><div><b>Chat model</b><small>{current||'Not configured'}</small></div><button className="primary" disabled={!current||save.isPending} onClick={()=>save.mutate(current)}>Save selection</button></div><div className="settings-grid">{(q.data?.models??[]).map(m=><button className={`setting-card ${current===m.id?'selected':''}`} key={m.id} onClick={()=>setSelected(m.id)}><div className="setting-card-header"><div><b>{m.name}</b><small>{m.provider}</small></div>{current===m.id&&<span className="type-badge">Selected</span>}</div><p>{m.provider==='ollama'?'Discovered locally':'Configured cloud model'}</p></button>)}</div></article></State></PageFrame>}
function ProjectsPage(){const q=useQuery({queryKey:['projects'],queryFn:()=>projects.list()});const [name,setName]=useState('');const [description,setDescription]=useState('');const qc=useQueryClient();const create=useMutation({mutationFn:()=>projects.create({name:name.trim(),description:description.trim()||undefined}),onSuccess:()=>{setName('');setDescription('');qc.invalidateQueries({queryKey:['projects']})}});return <PageFrame eyebrow="WORKSPACE" title="Projects" description="Track the work JARVIS is helping you move forward." action={<form className="project-form" onSubmit={e=>{e.preventDefault();if(name.trim())create.mutate()}}><input aria-label="Project name" value={name} onChange={e=>setName(e.target.value)} placeholder="New project name"/><button className="primary" disabled={!name.trim()||create.isPending}>＋ Add project</button></form>}><ListCard query={q} items={(q.data?.projects??[]) as Project[]} empty="No projects yet" render={p=><div className="artifact" key={p.id}><div><b>{p.name}</b><small>{p.status}{p.description?` · ${p.description}`:''}</small></div><span className="type-badge">{p.created_at?new Date(p.created_at).toLocaleDateString():'Active'}</span></div>}/></PageFrame>}
function KnowledgePage(){const [term,setTerm]=useState('');const [search,setSearch]=useState('');const q=useQuery({queryKey:['knowledge',search],queryFn:()=>search?knowledge.search(search,50):knowledge.list({limit:50})});const stats=useQuery({queryKey:['knowledge','statistics'],queryFn:knowledge.statistics});const items=(search?q.data?.knowledge:q.data?.knowledge)??[];return <PageFrame eyebrow="INTELLIGENCE" title="Knowledge" description="Browse the principles, patterns, and facts JARVIS has retained." action={<form className="search-form" onSubmit={e=>{e.preventDefault();setSearch(term.trim())}}><input aria-label="Search knowledge" value={term} onChange={e=>setTerm(e.target.value)} placeholder="Search knowledge"/><button className="primary">Search</button></form>}><State query={stats}><article className="wide knowledge-summary"><div><small>Knowledge items</small><b>{stats.data?.total_knowledge_items}</b></div><div><small>Experiences</small><b>{stats.data?.total_experiences}</b></div><div><small>Patterns</small><b>{stats.data?.total_patterns}</b></div><div><small>Failures</small><b>{stats.data?.total_failures}</b></div></article></State><ListCard query={q} items={items as KnowledgeItem[]} empty={search?'No matching knowledge':'No knowledge captured yet'} render={item=><div className="artifact" key={item.knowledge_id}><div><b>{item.claim}</b><small>{item.category} · {Math.round(item.confidence*100)}% confidence · {item.tags.length?item.tags.join(', '):'No tags'}</small></div><span className="type-badge">{item.evidence_count} evidence</span></div>}/></PageFrame>}
function ChatPage(){const [input,setInput]=useState('');const [messages,setMessages]=useState<{role:string;text:string}[]>([]);const group=useQuery({queryKey:['models','groups'],queryFn:models.groups});const mutation=useMutation({mutationFn:(text:string)=>chat.send(text,group.data?.groups?.chat||''),onSuccess:(data)=>setMessages(m=>[...m,{role:'assistant',text:data.response}])});const send=()=>{const text=input.trim();if(!text||mutation.isPending)return;setMessages(m=>[...m,{role:'user',text}]);setInput('');mutation.mutate(text)};return <PageFrame eyebrow="CHAT" title="JARVIS" description="Ask a question or give a task."><div className="chat chat-clean"><div className="chat-toolbar"><span className="status-dot"/> <span>Online</span><span className="chat-hint">Enter to send · Shift+Enter for a new line</span></div><div className="messages">{messages.length===0?<EmptyState title="What can I help with?" description="Ask JARVIS to research, plan, explain, or execute a task."/>:messages.map((m,i)=><div className={`message ${m.role}`} key={i}><div className="bubble">{m.text}</div></div>)}{mutation.isPending&&<div className="message assistant"><div className="bubble typing">Thinking…</div></div>}{mutation.isError&&<div className="error">Unable to reach JARVIS. <button onClick={()=>mutation.reset()}>Retry</button></div>}</div><form className="composer" onSubmit={e=>{e.preventDefault();send()}}><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Message JARVIS…" aria-label="Message JARVIS" /><button type="submit" disabled={mutation.isPending||!input.trim()} aria-label="Send message">{mutation.isPending?'…':'↑'}</button></form></div></PageFrame>}
function RemindersPage(){const q=useQuery({queryKey:['reminders'],queryFn:reminders.list});const qc=useQueryClient();const remove=useMutation({mutationFn:(id:number)=>reminders.delete(id),onSuccess:()=>qc.invalidateQueries({queryKey:['reminders']})});return <PageFrame eyebrow="WORKSPACE" title="Reminders" description="Scheduled reminders for your account."><ListCard query={q} items={q.data??[]} empty="No reminders" render={r=><div className="artifact" key={r.id}><div><b>{r.title}</b><small>{new Date(r.remind_at).toLocaleString()} · {r.repeat||'none'}</small></div><button onClick={()=>remove.mutate(r.id)} disabled={remove.isPending}>Delete</button></div>}/></PageFrame>}
function UnavailablePage({page}:{page:Page}){const details:Record<string,string>={files:'The file browser API is not exposed by the backend yet. Artifacts remain available for generated files.',notes:'The notes API is not exposed by the backend yet. No notes are fabricated here.'};return <PageFrame eyebrow={page.group.toUpperCase()} title={page.label} description="This workspace is ready for a backend connection."><article className="wide"><EmptyState title={`${page.label} is awaiting its API`} description={details[page.key]||'This route has no backend endpoint yet.'}/></article></PageFrame>}
function NotesPage(){const q=useQuery({queryKey:['notes'],queryFn:notes.list});const qc=useQueryClient();const remove=useMutation({mutationFn:(id:number)=>notes.delete(id),onSuccess:()=>qc.invalidateQueries({queryKey:['notes']})});const items=Array.isArray(q.data)?q.data:[];return <PageFrame eyebrow="WORKSPACE" title="Notes" description="Persistent notes for your account."><ListCard query={q} items={items} empty="No notes" render={n=><div className="artifact" key={n.id}><div><b>{n.title}</b><small>{n.content||'Empty note'} · {new Date(n.updated_at).toLocaleString()}</small></div><button onClick={()=>remove.mutate(n.id)} disabled={remove.isPending}>Delete</button></div>}/></PageFrame>}
function FilesPage(){const q=useQuery({queryKey:['files'],queryFn:()=>files.list()});const items=q.data?.entries??[];return <PageFrame eyebrow="WORKSPACE" title="Files" description="Browse the confined JARVIS data workspace."><ListCard query={q} items={items} empty="No files" render={f=><div className="artifact" key={f.name}><div><b>{f.name}</b><small>{f.is_dir?'Folder':`${f.size} bytes`} · {new Date(f.modified).toLocaleString()}</small></div></div>}/></PageFrame>}
function PageRoute({page}:{page:Page}){switch(page.key){case'dashboard':return <DashboardPage/>;case'activity':return <ActivityPage/>;case'agents':return <AgentsPage/>;case'workflows':return <WorkflowsPage/>;case'plans':return <PlansPage/>;case'schedules':return <SchedulesPage/>;case'research':return <ResearchPage/>;case'artifacts':return <ArtifactsPage/>;case'analytics':return <AnalyticsPage/>;case'memory':return <MemoryPage/>;case'diagnostics':return <DiagnosticsPage/>;case'settings':return <SettingsPage/>;case'models':return <ModelsPage/>;case'chat':return <ChatPage/>;case'projects':return <ProjectsPage/>;case'knowledge':return <KnowledgePage/>;case'reminders':return <RemindersPage/>;case'notes':return <NotesPage/>;case'files':return <FilesPage/>;default:return <UnavailablePage page={page}/>}}
