"""Phase 10 — Adaptive Behavior System data models.

The system never modifies source code directly. It adjusts
named "behavior knobs" — typed, ranged, auditable parameters
that are loaded by the existing subsystems at runtime.
"""

from __future__ import annotations

import enum
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any


class KnobCategory(str, enum.Enum):
    """Which subsystem a knob affects."""
    PLANNER = "planner"
    RESEARCH = "research"
    CODING = "coding"
    SCHEDULER = "scheduler"
    SYNTHESIZER = "synthesizer"
    ROUTING = "routing"
    GENERAL = "general"


class ExperimentStatus(str, enum.Enum):
    PLANNED = "PLANNED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    REVERTED = "REVERTED"


@dataclass
class BehaviorKnob:
    """A named, typed, ranged parameter that controls system behavior.

    Stored in knobs.json and loaded by subsystems at runtime.
    """
    name: str                               # e.g., "research.min_sources"
    category: KnobCategory                  # which subsystem
    current_value: Any                      # current active value
    default_value: Any                      # factory default for rollback
    min_value: float | None = None          # numeric lower bound (if numeric)
    max_value: float | None = None          # numeric upper bound (if numeric)
    allowed_values: list[Any] | None = None # categorical allowed values
    description: str = ""
    tags: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "category": self.category.value,
            "current_value": self.current_value,
            "default_value": self.default_value,
            "min_value": self.min_value,
            "max_value": self.max_value,
            "allowed_values": self.allowed_values,
            "description": self.description,
            "tags": self.tags,
        }


@dataclass
class ImprovementProposal:
    """A proposed behavior change, generated by the ImprovementDetector.

    Converted by ProposalEngine into concrete knob changes.
    """
    proposal_id: str
    reason: str                             # why this change is suggested
    category: KnobCategory                  # which subsystem to change
    confidence: float                       # 0.0–1.0 how strong is the evidence
    source_knowledge_ids: list[str] = field(default_factory=list)
    source_experience_ids: list[str] = field(default_factory=list)
    suggested_change: str = ""              # human-readable description
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "proposal_id": self.proposal_id,
            "reason": self.reason,
            "category": self.category.value,
            "confidence": self.confidence,
            "suggested_change": self.suggested_change,
        }


@dataclass
class KnobChange:
    """A concrete change to one knob."""
    knob_name: str
    new_value: Any
    reason: str = ""


@dataclass
class Experiment:
    """An A/B test comparing current behavior against a candidate."""
    experiment_id: str
    proposal_id: str
    knob_changes: list[KnobChange]
    status: ExperimentStatus = ExperimentStatus.PLANNED
    start_time: datetime | None = None
    end_time: datetime | None = None
    control_metrics: dict[str, float] = field(default_factory=dict)
    candidate_metrics: dict[str, float] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "experiment_id": self.experiment_id,
            "proposal_id": self.proposal_id,
            "changes": [{"knob": c.knob_name, "to": c.new_value} for c in self.knob_changes],
            "status": self.status.value,
            "control_metrics": self.control_metrics,
            "candidate_metrics": self.candidate_metrics,
        }


@dataclass
class MetricComparison:
    """Comparison of a single metric between control and candidate."""
    metric_name: str
    control_mean: float
    candidate_mean: float
    delta: float                            # candidate - control
    improvement: bool                       # True if delta is in the desired direction
    sample_size_control: int = 0
    sample_size_candidate: int = 0


@dataclass
class ExperimentResult:
    """Outcome of a completed experiment."""
    experiment_id: str
    metric_comparisons: list[MetricComparison]
    overall_improvement: bool               # True if metrics improved on balance
    summary: str = ""


# ── Knob definitions ─────────────────────────────────────────────────

KNOB_REGISTRY: dict[str, BehaviorKnob] = {
    "research.min_sources": BehaviorKnob(
        name="research.min_sources",
        category=KnobCategory.RESEARCH,
        current_value=2,
        default_value=2,
        min_value=1,
        max_value=10,
        description="Minimum number of sources required per research task",
        tags=["research", "quality"],
    ),
    "coding.simulation_required": BehaviorKnob(
        name="coding.simulation_required",
        category=KnobCategory.CODING,
        current_value=False,
        default_value=False,
        allowed_values=[True, False],
        description="Whether ChangeSimulation must run before refactor execution",
        tags=["coding", "safety"],
    ),
    "coding.safety_threshold": BehaviorKnob(
        name="coding.safety_threshold",
        category=KnobCategory.CODING,
        current_value=0.7,
        default_value=0.7,
        min_value=0.0,
        max_value=1.0,
        description="Risk score threshold below which a change is considered safe",
        tags=["coding", "safety"],
    ),
    "planner.inject_domain_patterns": BehaviorKnob(
        name="planner.inject_domain_patterns",
        category=KnobCategory.PLANNER,
        current_value=True,
        default_value=True,
        allowed_values=[True, False],
        description="Whether to inject domain patterns from KnowledgeStore into planner prompt",
        tags=["planner", "knowledge"],
    ),
    "planner.inject_failure_warnings": BehaviorKnob(
        name="planner.inject_failure_warnings",
        category=KnobCategory.PLANNER,
        current_value=True,
        default_value=True,
        allowed_values=[True, False],
        description="Whether to inject failure warnings from KnowledgeStore into planner prompt",
        tags=["planner", "knowledge"],
    ),
    "synthesizer.min_evidence_pattern": BehaviorKnob(
        name="synthesizer.min_evidence_pattern",
        category=KnobCategory.SYNTHESIZER,
        current_value=2,
        default_value=2,
        min_value=1,
        max_value=10,
        description="Minimum evidence count to create a pattern knowledge item",
        tags=["synthesizer", "quality"],
    ),
    "synthesizer.min_evidence_principle": BehaviorKnob(
        name="synthesizer.min_evidence_principle",
        category=KnobCategory.SYNTHESIZER,
        current_value=3,
        default_value=3,
        min_value=2,
        max_value=20,
        description="Minimum evidence count to create a principle knowledge item",
        tags=["synthesizer", "quality"],
    ),
    "synthesizer.high_confidence_threshold": BehaviorKnob(
        name="synthesizer.high_confidence_threshold",
        category=KnobCategory.SYNTHESIZER,
        current_value=0.8,
        default_value=0.8,
        min_value=0.5,
        max_value=1.0,
        description="Success rate threshold for positive pattern detection",
        tags=["synthesizer", "quality"],
    ),
    "scheduler.urgency_bonus": BehaviorKnob(
        name="scheduler.urgency_bonus",
        category=KnobCategory.SCHEDULER,
        current_value=30,
        default_value=30,
        min_value=0,
        max_value=100,
        description="Score bonus for pending/running activities",
        tags=["scheduler"],
    ),
    "scheduler.retry_bonus": BehaviorKnob(
        name="scheduler.retry_bonus",
        category=KnobCategory.SCHEDULER,
        current_value=50,
        default_value=50,
        min_value=0,
        max_value=100,
        description="Score bonus for previously failed activities",
        tags=["scheduler"],
    ),
    "scheduler.waiting_bonus_per_minute": BehaviorKnob(
        name="scheduler.waiting_bonus_per_minute",
        category=KnobCategory.SCHEDULER,
        current_value=2,
        default_value=2,
        min_value=0,
        max_value=20,
        description="Per-minute waiting time bonus",
        tags=["scheduler"],
    ),

    # ── Planner strategy weight knobs ─────────────────────────────────
    "planner.strategy_weight.flutter": BehaviorKnob(
        name="planner.strategy_weight.flutter",
        category=KnobCategory.PLANNER,
        current_value=1.0,
        default_value=1.0,
        min_value=0.0,
        max_value=2.0,
        description="Weight multiplier for Flutter strategy recommendation",
        tags=["planner", "strategy"],
    ),
    "planner.strategy_weight.native_android": BehaviorKnob(
        name="planner.strategy_weight.native_android",
        category=KnobCategory.PLANNER,
        current_value=1.0,
        default_value=1.0,
        min_value=0.0,
        max_value=2.0,
        description="Weight multiplier for Native Android strategy recommendation",
        tags=["planner", "strategy"],
    ),
    "planner.strategy_weight.react_native": BehaviorKnob(
        name="planner.strategy_weight.react_native",
        category=KnobCategory.PLANNER,
        current_value=1.0,
        default_value=1.0,
        min_value=0.0,
        max_value=2.0,
        description="Weight multiplier for React Native strategy recommendation",
        tags=["planner", "strategy"],
    ),
    "planner.strategy_weight.web_pwa": BehaviorKnob(
        name="planner.strategy_weight.web_pwa",
        category=KnobCategory.PLANNER,
        current_value=1.0,
        default_value=1.0,
        min_value=0.0,
        max_value=2.0,
        description="Weight multiplier for Web PWA strategy recommendation",
        tags=["planner", "strategy"],
    ),
    "planner.strategy_weight.ios_native": BehaviorKnob(
        name="planner.strategy_weight.ios_native",
        category=KnobCategory.PLANNER,
        current_value=1.0,
        default_value=1.0,
        min_value=0.0,
        max_value=2.0,
        description="Weight multiplier for iOS Native strategy recommendation",
        tags=["planner", "strategy"],
    ),
    "planner.strategy_weight.backend_first": BehaviorKnob(
        name="planner.strategy_weight.backend_first",
        category=KnobCategory.PLANNER,
        current_value=1.0,
        default_value=1.0,
        min_value=0.0,
        max_value=2.0,
        description="Weight multiplier for Backend-First strategy recommendation",
        tags=["planner", "strategy"],
    ),
}

DEFAULT_KNOBS_JSON = str(Path("data") / "knobs.json")
