from __future__ import annotations

from typing import Protocol


class WorkerEndpoint(Protocol):
    async def execute(self, request): ...
    async def health(self): ...
    async def heartbeat(self): ...
    async def shutdown(self): ...


class WorkerControl(Protocol):
    async def heartbeat(self): ...
    async def shutdown(self): ...
