"""Line-by-line oriented audit: classify every .py file in the repo.

Categories:
  STUB   - contains the autogenerated "Auto-reconstructed backend component"
           marker and/or the DynamicStub swaller pattern.
  EMPTY  - <= 5 effective lines (only whitespace/comments/imports).
  THIN   - small file (<40 code lines) whose function bodies are all pass/...
  REAL   - everything else.
"""
from __future__ import annotations

import os
import re
import sys
from collections import defaultdict

STUB_MARKER = "Auto-reconstructed" + " backend component"
DYN = "DynamicStub"
SKIP_DIRS = {".git", "__pycache__", "node_modules", "venv", ".venv", "dist",
             "build", ".hypothesis", ".pytest_cache", "jarvis.egg-info",
             "jarvis-export"}

results: dict[str, list[tuple[str, int, str]]] = defaultdict(list)


def classify(path: str) -> tuple[str, int, str]:
    try:
        with open(path, encoding="utf-8", errors="ignore") as fh:
            src = fh.read()
    except OSError:
        return "ERR", 0, ""
    lines = src.splitlines()
    code = [l for l in lines if l.strip() and not l.strip().startswith("#")]
    reasons = []
    is_stub = STUB_MARKER in src or ("class DynamicStub" in src and "def __getattr__" in src)
    if STUB_MARKER in src:
        reasons.append("marker")
    if "class DynamicStub" in src:
        reasons.append("dynstub")
    if is_stub:
        return "STUB", len(code), ",".join(reasons)
    if len(code) <= 5:
        return "EMPTY", len(code), "tiny"
    # thin: all def/async def bodies are pass/.../return None only?
    bodies = re.findall(r"\ndef [^(]+\([^)]*\)[^:]*:\n((?:\s+(?:pass|\.\.\.|return None|#.*|\"\"\"[^\"]*\"\"\")\n?)*)", src)
    if bodies and all(b.strip() in ("pass", "...", "") or
                      all(l.strip() in ("pass", "...", "") or l.strip().startswith("#")
                          for l in b.splitlines() if l.strip())
                      for b in bodies) and len(bodies) >= 3:
        return "THIN", len(code), f"{len(bodies)} all-pass defs"
    return "REAL", len(code), ""


for dirpath, dirnames, filenames in os.walk("."):
    dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
    for name in filenames:
        if not name.endswith(".py"):
            continue
        path = os.path.join(dirpath, name).replace("\\", "/")
        rel = path[2:]
        top = rel.split("/")[0] if "/" in rel else "(root)"
        cat, n, why = classify(path)
        results[top].append((rel, n, why))

tot = defaultdict(int)
stub_files = []
print(f"{'top dir':28s} {'files':>6} {'STUB':>6} {'EMPTY':>6} {'THIN':>5} {'REAL':>6} {'LOC':>8} {'stub%':>6}")
for top in sorted(results):
    files = results[top]
    c = defaultdict(int)
    loc = 0
    for rel, n, why in files:
        cat = classify("./" + rel)[0]
        c[cat] += 1
        loc += n
        if cat == "STUB":
            stub_files.append(rel)
    tot["files"] += len(files)
    tot[c["STUB"]] += c["STUB"]
    tot["EMPTY"] += c["EMPTY"]
    tot["THIN"] += c["THIN"]
    tot["REAL"] += c["REAL"]
    tot["LOC"] += loc
    pct = 100.0 * c["STUB"] / len(files) if files else 0
    flag = " <<<" if c["STUB"] >= 5 else ""
    print(f"{top:28s} {len(files):6d} {c['STUB']:6d} {c['EMPTY']:6d} {c['THIN']:5d} {c['REAL']:6d} {loc:8d} {pct:5.1f}%{flag}")
print("-" * 90)
print(f"{'TOTAL':28s} {tot['files']:6d} {tot['STUB']:6d} {tot['EMPTY']:6d} {tot['THIN']:5d} {tot['REAL']:6d} {tot['LOC']:8d} "
      f"{100.0*tot['STUB']/tot['files']:5.1f}%")

with open("audit_stub_list.txt", "w", encoding="utf-8") as fh:
    fh.write("\n".join(sorted(stub_files)))
print(f"\nfull stub list written to audit_stub_list.txt ({len(stub_files)} files)")
