"""Independent stub counter.

Counts how many `.py` files still contain the autogenerated stub marker.
Deliberately ignores compiled `__pycache__/*.pyc` files so the number cannot
be inflated. Run from the repo root:  python scripts/count_stubs.py

This is the single progress metric: the number must go DOWN over time.
"""
from __future__ import annotations

import os
import sys
from collections import defaultdict

# Split so this script does not match its own marker literal.
MARKER = "Auto-reconstructed" + " backend component"

# Backup copies must not inflate/deflate the metric: only live source counts.
SKIP_DIRS = {".git", "rebuild_backlog"}


def count(base: str) -> tuple[int, int]:
    total = stubs = 0
    for dirpath, _dirnames, filenames in os.walk(base):
        parts = dirpath.replace("\\", "/").split("/")
        if ".git" in parts or any(d in SKIP_DIRS for d in parts):
            continue
        for name in filenames:
            if not name.endswith(".py"):
                continue
            total += 1
            path = os.path.join(dirpath, name)
            try:
                with open(path, "r", encoding="utf-8", errors="ignore") as fh:
                    if MARKER in fh.read():
                        stubs += 1
            except OSError:
                pass
    return stubs, total


def main() -> int:
    root = sys.argv[1] if len(sys.argv) > 1 else "."
    stubs, total = count(root)
    pct = (100.0 * stubs / total) if total else 0.0
    print(f"STUB COUNT ({root}): {stubs} / {total} .py files ({pct:.1f}%)")

    per = defaultdict(lambda: [0, 0])
    core = os.path.join(root, "core")
    if os.path.isdir(core):
        for dirpath, _dirnames, filenames in os.walk(core):
            for name in filenames:
                if not name.endswith(".py"):
                    continue
                rel = os.path.relpath(os.path.join(dirpath, name), core)
                pkg = rel.split(os.sep)[0]
                per[pkg][0] += 1
                try:
                    with open(os.path.join(dirpath, name), encoding="utf-8",
                              errors="ignore") as fh:
                        if MARKER in fh.read():
                            per[pkg][1] += 1
                except OSError:
                    pass
        print("Stub-heavy core packages:")
        for pkg, (tot, st) in sorted(per.items(), key=lambda kv: -kv[1][1]):
            if st:
                print(f"  {pkg:28s} {st:3d}/{tot}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
