"""Pipeline stages — canonical 26-stage set (ADR-007 + ADR-009).

Each stage lives in its own module (ownership rules) and is re-exported
here as the single import surface for the architecture contract.
"""
from core.pipeline.stages._canonical import (  # noqa: F401
    DEFAULT_STAGES,
    ActivityStage,
    AuthenticationStage,
    AuthorizationStage,
    CapabilitySelectionStage,
    ContextRetrievalStage,
    EpistemicTaggingStage,
    ExecutionStage,
    ExplainabilityStage,
    FormatterStage,
    IntentStage,
    KnowledgeStage,
    LearningStage,
    LiteLLMProvider,
    LoadContextStage,
    MemoryStage,
    MetricsStage,
    MockProvider,
    NotificationStage,
    OllamaFallbackProvider,
    PlanValidatorStage,
    PlannerStage,
    PolicyOptimizationStage,
    Provider,
    ProviderResult,
    RateLimitStage,
    ReasonerStage,
    ReasoningStage,
    ReceiveStage,
    ReflectionStage,
    ResourceAccessStage,
    TenantResolutionStage,
    VerificationStage,
)

__all__ = [
    "DEFAULT_STAGES",
    "ReceiveStage", "LoadContextStage", "AuthenticationStage",
    "TenantResolutionStage", "AuthorizationStage", "ResourceAccessStage",
    "RateLimitStage", "IntentStage", "ContextRetrievalStage",
    "KnowledgeStage", "ReasoningStage", "ReasonerStage", "PlannerStage",
    "PlanValidatorStage", "ActivityStage", "CapabilitySelectionStage",
    "ExecutionStage", "VerificationStage", "EpistemicTaggingStage",
    "ReflectionStage", "LearningStage", "PolicyOptimizationStage",
    "MemoryStage", "NotificationStage", "MetricsStage",
    "ExplainabilityStage", "FormatterStage",
    "LiteLLMProvider", "OllamaFallbackProvider", "Provider",
    "ProviderResult", "MockProvider",
]
